# Training configuration for IMDB sentiment analysis

# Model configuration
model:
  name: "bert-base-uncased"
  num_labels: 2
  dropout_rate: 0.1
  gradient_checkpointing: false

# Training parameters
training:
  seed: 42
  num_epochs: 5
  early_stopping_patience: 3
  early_stopping_min_delta: 0.01
  fp16: false
  max_grad_norm: 1.0
  batch_size: 48

# Optimizer configuration
optimizer:
  type: "adamw"
  learning_rate: 2.0e-5
  weight_decay: 0.01
  adam_epsilon: 1.0e-8
  adam_betas: [0.9, 0.999]
  scheduler: "linear"
  warmup_ratio: 0.1
  lr_reduction_factor: 0.5
  lr_patience: 2

# Logging configuration
logging:
  monitor: "f1"
  mode: "max"
  save_model: true
  save_best_only: true
  wandb_project: "imdb-bert-sentiment"
